# Generated by Django 4.2.2 on 2023-08-23 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiuser',
            name='cat',
            field=models.CharField(choices=[('Пользователь', 'пользователь'), ('Поставщик', 'поставщик')], default=1, max_length=16),
            preserve_default=False,
        ),
    ]
