# Generated by Django 4.2.2 on 2023-08-29 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_purchase_remove_room_hotel_rename_hotel_storage_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Purchase',
            new_name='Product',
        ),
    ]
