# Generated by Django 4.2.2 on 2023-08-29 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_product_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='name',
            field=models.CharField(default=0, max_length=128),
            preserve_default=False,
        ),
    ]
