# Generated by Django 4.2.2 on 2023-08-30 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_product_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
    ]
